language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

before_script:
  - cd salamander
  - glide install

script:
  - go vet
  - go test $(glide nv) -v
