language: go
sudo: required

go:
  - 1.8.x
  - 1.9.x

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine
  - docker --version
  - docker build -t salamander .
  - cd salamander

install:
  - glide install

script:
  - go vet
  - go test $(glide nv) -v
