language: go

go:
  - 1.8.x
  - 1.9.x

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

services:
  - docker

before_install:
  - docker build -t salamander .
  - cd salamander

install:
  - glide install

script:
  - go vet
  - go test $(glide nv) -v
